import type { Metadata } from "next";
import {Outfit} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastContainer } from 'react-toastify';


const geistSans = Outfit({
  subsets:['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body
          className={`${geistSans.className} `}
          >
          {children}
          <ToastContainer/>
        </body>
      </ClerkProvider>
    </html>
  );
}
